import '../styles/globals.css'
import Head from "next/head";

function MyApp({ Component, pageProps }) {
  return (
  
    
  <div className='respo'>  
     <Head>
        <title>SinkedIn </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://scontent.fcok10-1.fna.fbcdn.net/v/t1.18169-9/208224_147407701991586_4424088_n.jpg?_nc_cat=108&ccb=1-7&_nc_sid=cdbe9c&_nc_ohc=6fgQG-gtvd8AX95D9cN&_nc_ht=scontent.fcok10-1.fna&oh=00_AfAMgyZwHUua1NquG8vc6yT1tVq8NCTrjXLllanugkZY6g&oe=63A328FF"/>
     </Head>
    <Component {...pageProps} />
  </div>

  )
}

export default MyApp
